# Site settings
title: Military Cyber Professionals Association, Dayton Chapter
email: contact.dayton@milcyber.org
description: > # this means to ignore newlines until "baseurl:"
  We are a team of Soldiers, Sailors, Airmen, Marines, Veterans and others
  interested in the development of the American military cyber profession. Our
  members are interdisciplinary, as such a diverse set of perspectives is
  needed to develop cyberspace as an entire domain. Also included in our ranks
  are other government employees, contractors, academics, industry leaders,
  foreign allies, and private citizens.
baseurl: "" 
url: "https://dayton.milcyber.org"
github_username:  mcpa-dayton

# Build settings
markdown: kramdown
permalink: /news/:year/:month/:day/:title
gems:
  - jekyll-sitemap


